apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::937525203833:user/Cmiey
      username: cmiey
      groups:
        - system:masters
